// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/modules/leaderboard/infrastructure/repositories/interface.go
//
// Generated by this command:
//
//	mockgen -source=./app/modules/leaderboard/infrastructure/repositories/interface.go -destination=./app/modules/leaderboard/infrastructure/repositories/mocks/mock_db.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	leaderboardtypes "github.com/Black-And-White-Club/frolf-bot-shared/types/leaderboard"
	leaderboarddb "github.com/Black-And-White-Club/frolf-bot/app/modules/leaderboard/infrastructure/repositories"
	gomock "go.uber.org/mock/gomock"
)

// MockLeaderboardDB is a mock of LeaderboardDB interface.
type MockLeaderboardDB struct {
	ctrl     *gomock.Controller
	recorder *MockLeaderboardDBMockRecorder
	isgomock struct{}
}

// MockLeaderboardDBMockRecorder is the mock recorder for MockLeaderboardDB.
type MockLeaderboardDBMockRecorder struct {
	mock *MockLeaderboardDB
}

// NewMockLeaderboardDB creates a new mock instance.
func NewMockLeaderboardDB(ctrl *gomock.Controller) *MockLeaderboardDB {
	mock := &MockLeaderboardDB{ctrl: ctrl}
	mock.recorder = &MockLeaderboardDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaderboardDB) EXPECT() *MockLeaderboardDBMockRecorder {
	return m.recorder
}

// AssignTag mocks base method.
func (m *MockLeaderboardDB) AssignTag(ctx context.Context, userID leaderboardtypes.UserID, tagNumber int, source leaderboarddb.ServiceUpdateTagSource, updateID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignTag", ctx, userID, tagNumber, source, updateID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignTag indicates an expected call of AssignTag.
func (mr *MockLeaderboardDBMockRecorder) AssignTag(ctx, userID, tagNumber, source, updateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignTag", reflect.TypeOf((*MockLeaderboardDB)(nil).AssignTag), ctx, userID, tagNumber, source, updateID)
}

// CheckTagAvailability mocks base method.
func (m *MockLeaderboardDB) CheckTagAvailability(ctx context.Context, tagNumber int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckTagAvailability", ctx, tagNumber)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckTagAvailability indicates an expected call of CheckTagAvailability.
func (mr *MockLeaderboardDBMockRecorder) CheckTagAvailability(ctx, tagNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckTagAvailability", reflect.TypeOf((*MockLeaderboardDB)(nil).CheckTagAvailability), ctx, tagNumber)
}

// CreateLeaderboard mocks base method.
func (m *MockLeaderboardDB) CreateLeaderboard(ctx context.Context, leaderboard *leaderboarddb.Leaderboard) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLeaderboard", ctx, leaderboard)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLeaderboard indicates an expected call of CreateLeaderboard.
func (mr *MockLeaderboardDBMockRecorder) CreateLeaderboard(ctx, leaderboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLeaderboard", reflect.TypeOf((*MockLeaderboardDB)(nil).CreateLeaderboard), ctx, leaderboard)
}

// DeactivateLeaderboard mocks base method.
func (m *MockLeaderboardDB) DeactivateLeaderboard(ctx context.Context, leaderboardID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateLeaderboard", ctx, leaderboardID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateLeaderboard indicates an expected call of DeactivateLeaderboard.
func (mr *MockLeaderboardDBMockRecorder) DeactivateLeaderboard(ctx, leaderboardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateLeaderboard", reflect.TypeOf((*MockLeaderboardDB)(nil).DeactivateLeaderboard), ctx, leaderboardID)
}

// GetActiveLeaderboard mocks base method.
func (m *MockLeaderboardDB) GetActiveLeaderboard(ctx context.Context) (*leaderboarddb.Leaderboard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveLeaderboard", ctx)
	ret0, _ := ret[0].(*leaderboarddb.Leaderboard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveLeaderboard indicates an expected call of GetActiveLeaderboard.
func (mr *MockLeaderboardDBMockRecorder) GetActiveLeaderboard(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveLeaderboard", reflect.TypeOf((*MockLeaderboardDB)(nil).GetActiveLeaderboard), ctx)
}

// GetTagByUserID mocks base method.
func (m *MockLeaderboardDB) GetTagByUserID(ctx context.Context, userID string) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagByUserID", ctx, userID)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagByUserID indicates an expected call of GetTagByUserID.
func (mr *MockLeaderboardDBMockRecorder) GetTagByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagByUserID", reflect.TypeOf((*MockLeaderboardDB)(nil).GetTagByUserID), ctx, userID)
}

// SwapTags mocks base method.
func (m *MockLeaderboardDB) SwapTags(ctx context.Context, requestorID, targetID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwapTags", ctx, requestorID, targetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SwapTags indicates an expected call of SwapTags.
func (mr *MockLeaderboardDBMockRecorder) SwapTags(ctx, requestorID, targetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwapTags", reflect.TypeOf((*MockLeaderboardDB)(nil).SwapTags), ctx, requestorID, targetID)
}

// UpdateLeaderboard mocks base method.
func (m *MockLeaderboardDB) UpdateLeaderboard(ctx context.Context, leaderboardData map[int]string, scoreUpdateID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLeaderboard", ctx, leaderboardData, scoreUpdateID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLeaderboard indicates an expected call of UpdateLeaderboard.
func (mr *MockLeaderboardDBMockRecorder) UpdateLeaderboard(ctx, leaderboardData, scoreUpdateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLeaderboard", reflect.TypeOf((*MockLeaderboardDB)(nil).UpdateLeaderboard), ctx, leaderboardData, scoreUpdateID)
}
