// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/modules/leaderboard/infrastructure/repositories/interface.go
//
// Generated by this command:
//
//	mockgen -source=./app/modules/leaderboard/infrastructure/repositories/interface.go -destination=./app/modules/leaderboard/infrastructure/repositories/mocks/mock_db.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	leaderboardtypes "github.com/Black-And-White-Club/frolf-bot-shared/types/leaderboard"
	sharedtypes "github.com/Black-And-White-Club/frolf-bot-shared/types/shared"
	leaderboarddb "github.com/Black-And-White-Club/frolf-bot/app/modules/leaderboard/infrastructure/repositories"
	bun "github.com/uptrace/bun"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CheckTagAvailability mocks base method.
func (m *MockRepository) CheckTagAvailability(ctx context.Context, guildID sharedtypes.GuildID, userID sharedtypes.DiscordID, tagNumber sharedtypes.TagNumber) (leaderboarddb.TagAvailabilityResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckTagAvailability", ctx, guildID, userID, tagNumber)
	ret0, _ := ret[0].(leaderboarddb.TagAvailabilityResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckTagAvailability indicates an expected call of CheckTagAvailability.
func (mr *MockRepositoryMockRecorder) CheckTagAvailability(ctx, guildID, userID, tagNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckTagAvailability", reflect.TypeOf((*MockRepository)(nil).CheckTagAvailability), ctx, guildID, userID, tagNumber)
}

// CreateLeaderboard mocks base method.
func (m *MockRepository) CreateLeaderboard(ctx context.Context, idb bun.IDB, guildID sharedtypes.GuildID, leaderboard *leaderboarddb.Leaderboard) (*leaderboarddb.Leaderboard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLeaderboard", ctx, idb, guildID, leaderboard)
	ret0, _ := ret[0].(*leaderboarddb.Leaderboard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLeaderboard indicates an expected call of CreateLeaderboard.
func (mr *MockRepositoryMockRecorder) CreateLeaderboard(ctx, idb, guildID, leaderboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLeaderboard", reflect.TypeOf((*MockRepository)(nil).CreateLeaderboard), ctx, idb, guildID, leaderboard)
}

// DeactivateLeaderboard mocks base method.
func (m *MockRepository) DeactivateLeaderboard(ctx context.Context, idb bun.IDB, guildID sharedtypes.GuildID, leaderboardID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateLeaderboard", ctx, idb, guildID, leaderboardID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateLeaderboard indicates an expected call of DeactivateLeaderboard.
func (mr *MockRepositoryMockRecorder) DeactivateLeaderboard(ctx, idb, guildID, leaderboardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateLeaderboard", reflect.TypeOf((*MockRepository)(nil).DeactivateLeaderboard), ctx, idb, guildID, leaderboardID)
}

// GetActiveLeaderboard mocks base method.
func (m *MockRepository) GetActiveLeaderboard(ctx context.Context, guildID sharedtypes.GuildID) (*leaderboarddb.Leaderboard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveLeaderboard", ctx, guildID)
	ret0, _ := ret[0].(*leaderboarddb.Leaderboard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveLeaderboard indicates an expected call of GetActiveLeaderboard.
func (mr *MockRepositoryMockRecorder) GetActiveLeaderboard(ctx, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveLeaderboard", reflect.TypeOf((*MockRepository)(nil).GetActiveLeaderboard), ctx, guildID)
}

// GetActiveLeaderboardIDB mocks base method.
func (m *MockRepository) GetActiveLeaderboardIDB(ctx context.Context, idb bun.IDB, guildID sharedtypes.GuildID) (*leaderboarddb.Leaderboard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveLeaderboardIDB", ctx, idb, guildID)
	ret0, _ := ret[0].(*leaderboarddb.Leaderboard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveLeaderboardIDB indicates an expected call of GetActiveLeaderboardIDB.
func (mr *MockRepositoryMockRecorder) GetActiveLeaderboardIDB(ctx, idb, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveLeaderboardIDB", reflect.TypeOf((*MockRepository)(nil).GetActiveLeaderboardIDB), ctx, idb, guildID)
}

// GetTagByUserID mocks base method.
func (m *MockRepository) GetTagByUserID(ctx context.Context, guildID sharedtypes.GuildID, userID sharedtypes.DiscordID) (*sharedtypes.TagNumber, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagByUserID", ctx, guildID, userID)
	ret0, _ := ret[0].(*sharedtypes.TagNumber)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagByUserID indicates an expected call of GetTagByUserID.
func (mr *MockRepositoryMockRecorder) GetTagByUserID(ctx, guildID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagByUserID", reflect.TypeOf((*MockRepository)(nil).GetTagByUserID), ctx, guildID, userID)
}

// UpdateLeaderboard mocks base method.
func (m *MockRepository) UpdateLeaderboard(ctx context.Context, idb bun.IDB, guildID sharedtypes.GuildID, leaderboardData leaderboardtypes.LeaderboardData, updateID sharedtypes.RoundID, source sharedtypes.ServiceUpdateSource) (*leaderboarddb.Leaderboard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLeaderboard", ctx, idb, guildID, leaderboardData, updateID, source)
	ret0, _ := ret[0].(*leaderboarddb.Leaderboard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLeaderboard indicates an expected call of UpdateLeaderboard.
func (mr *MockRepositoryMockRecorder) UpdateLeaderboard(ctx, idb, guildID, leaderboardData, updateID, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLeaderboard", reflect.TypeOf((*MockRepository)(nil).UpdateLeaderboard), ctx, idb, guildID, leaderboardData, updateID, source)
}
