// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Black-And-White-Club/tcr-bot/app/types (interfaces: Publisher)
//
// Generated by this command:
//
//	mockgen -destination=internal/testutils/publisher_mock.go -package=testutils github.com/Black-And-White-Club/tcr-bot/app/types Publisher
//

// Package testutils is a generated GoMock package.
package testutils

import (
	reflect "reflect"

	types "github.com/Black-And-White-Club/tcr-bot/app/types"
	gomock "go.uber.org/mock/gomock"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockPublisher) Publish(topic string, msg types.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", topic, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockPublisherMockRecorder) Publish(topic, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPublisher)(nil).Publish), topic, msg)
}
