// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/modules/round/infrastructure/repositories/interface.go
//
// Generated by this command:
//
//	mockgen -source=./app/modules/round/infrastructure/repositories/interface.go -destination=./app/modules/round/infrastructure/repositories/mocks/mock_db.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	roundtypes "github.com/Black-And-White-Club/frolf-bot-shared/types/round"
	sharedtypes "github.com/Black-And-White-Club/frolf-bot-shared/types/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateRound mocks base method.
func (m *MockRepository) CreateRound(ctx context.Context, guildID sharedtypes.GuildID, round *roundtypes.Round) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRound", ctx, guildID, round)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRound indicates an expected call of CreateRound.
func (mr *MockRepositoryMockRecorder) CreateRound(ctx, guildID, round any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRound", reflect.TypeOf((*MockRepository)(nil).CreateRound), ctx, guildID, round)
}

// DeleteRound mocks base method.
func (m *MockRepository) DeleteRound(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRound", ctx, guildID, roundID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRound indicates an expected call of DeleteRound.
func (mr *MockRepositoryMockRecorder) DeleteRound(ctx, guildID, roundID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRound", reflect.TypeOf((*MockRepository)(nil).DeleteRound), ctx, guildID, roundID)
}

// GetEventMessageID mocks base method.
func (m *MockRepository) GetEventMessageID(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventMessageID", ctx, guildID, roundID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventMessageID indicates an expected call of GetEventMessageID.
func (mr *MockRepositoryMockRecorder) GetEventMessageID(ctx, guildID, roundID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventMessageID", reflect.TypeOf((*MockRepository)(nil).GetEventMessageID), ctx, guildID, roundID)
}

// GetParticipant mocks base method.
func (m *MockRepository) GetParticipant(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID, userID sharedtypes.DiscordID) (*roundtypes.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParticipant", ctx, guildID, roundID, userID)
	ret0, _ := ret[0].(*roundtypes.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipant indicates an expected call of GetParticipant.
func (mr *MockRepositoryMockRecorder) GetParticipant(ctx, guildID, roundID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipant", reflect.TypeOf((*MockRepository)(nil).GetParticipant), ctx, guildID, roundID, userID)
}

// GetParticipants mocks base method.
func (m *MockRepository) GetParticipants(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID) ([]roundtypes.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParticipants", ctx, guildID, roundID)
	ret0, _ := ret[0].([]roundtypes.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipants indicates an expected call of GetParticipants.
func (mr *MockRepositoryMockRecorder) GetParticipants(ctx, guildID, roundID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipants", reflect.TypeOf((*MockRepository)(nil).GetParticipants), ctx, guildID, roundID)
}

// GetParticipantsWithResponses mocks base method.
func (m *MockRepository) GetParticipantsWithResponses(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID, responses ...string) ([]roundtypes.Participant, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, guildID, roundID}
	for _, a := range responses {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetParticipantsWithResponses", varargs...)
	ret0, _ := ret[0].([]roundtypes.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipantsWithResponses indicates an expected call of GetParticipantsWithResponses.
func (mr *MockRepositoryMockRecorder) GetParticipantsWithResponses(ctx, guildID, roundID any, responses ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, guildID, roundID}, responses...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipantsWithResponses", reflect.TypeOf((*MockRepository)(nil).GetParticipantsWithResponses), varargs...)
}

// GetRound mocks base method.
func (m *MockRepository) GetRound(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID) (*roundtypes.Round, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRound", ctx, guildID, roundID)
	ret0, _ := ret[0].(*roundtypes.Round)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRound indicates an expected call of GetRound.
func (mr *MockRepositoryMockRecorder) GetRound(ctx, guildID, roundID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRound", reflect.TypeOf((*MockRepository)(nil).GetRound), ctx, guildID, roundID)
}

// GetRoundState mocks base method.
func (m *MockRepository) GetRoundState(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID) (roundtypes.RoundState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoundState", ctx, guildID, roundID)
	ret0, _ := ret[0].(roundtypes.RoundState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoundState indicates an expected call of GetRoundState.
func (mr *MockRepositoryMockRecorder) GetRoundState(ctx, guildID, roundID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoundState", reflect.TypeOf((*MockRepository)(nil).GetRoundState), ctx, guildID, roundID)
}

// GetUpcomingRounds mocks base method.
func (m *MockRepository) GetUpcomingRounds(ctx context.Context, guildID sharedtypes.GuildID) ([]*roundtypes.Round, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpcomingRounds", ctx, guildID)
	ret0, _ := ret[0].([]*roundtypes.Round)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpcomingRounds indicates an expected call of GetUpcomingRounds.
func (mr *MockRepositoryMockRecorder) GetUpcomingRounds(ctx, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpcomingRounds", reflect.TypeOf((*MockRepository)(nil).GetUpcomingRounds), ctx, guildID)
}

// GetUpcomingRoundsByParticipant mocks base method.
func (m *MockRepository) GetUpcomingRoundsByParticipant(ctx context.Context, guildID sharedtypes.GuildID, userID sharedtypes.DiscordID) ([]*roundtypes.Round, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpcomingRoundsByParticipant", ctx, guildID, userID)
	ret0, _ := ret[0].([]*roundtypes.Round)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpcomingRoundsByParticipant indicates an expected call of GetUpcomingRoundsByParticipant.
func (mr *MockRepositoryMockRecorder) GetUpcomingRoundsByParticipant(ctx, guildID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpcomingRoundsByParticipant", reflect.TypeOf((*MockRepository)(nil).GetUpcomingRoundsByParticipant), ctx, guildID, userID)
}

// RemoveParticipant mocks base method.
func (m *MockRepository) RemoveParticipant(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID, userID sharedtypes.DiscordID) ([]roundtypes.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveParticipant", ctx, guildID, roundID, userID)
	ret0, _ := ret[0].([]roundtypes.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveParticipant indicates an expected call of RemoveParticipant.
func (mr *MockRepositoryMockRecorder) RemoveParticipant(ctx, guildID, roundID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveParticipant", reflect.TypeOf((*MockRepository)(nil).RemoveParticipant), ctx, guildID, roundID, userID)
}

// UpdateEventMessageID mocks base method.
func (m *MockRepository) UpdateEventMessageID(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID, eventMessageID string) (*roundtypes.Round, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEventMessageID", ctx, guildID, roundID, eventMessageID)
	ret0, _ := ret[0].(*roundtypes.Round)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEventMessageID indicates an expected call of UpdateEventMessageID.
func (mr *MockRepositoryMockRecorder) UpdateEventMessageID(ctx, guildID, roundID, eventMessageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEventMessageID", reflect.TypeOf((*MockRepository)(nil).UpdateEventMessageID), ctx, guildID, roundID, eventMessageID)
}

// UpdateImportStatus mocks base method.
func (m *MockRepository) UpdateImportStatus(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID, importID, status, errorMessage, errorCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateImportStatus", ctx, guildID, roundID, importID, status, errorMessage, errorCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateImportStatus indicates an expected call of UpdateImportStatus.
func (mr *MockRepositoryMockRecorder) UpdateImportStatus(ctx, guildID, roundID, importID, status, errorMessage, errorCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateImportStatus", reflect.TypeOf((*MockRepository)(nil).UpdateImportStatus), ctx, guildID, roundID, importID, status, errorMessage, errorCode)
}

// UpdateParticipant mocks base method.
func (m *MockRepository) UpdateParticipant(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID, participant roundtypes.Participant) ([]roundtypes.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateParticipant", ctx, guildID, roundID, participant)
	ret0, _ := ret[0].([]roundtypes.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateParticipant indicates an expected call of UpdateParticipant.
func (mr *MockRepositoryMockRecorder) UpdateParticipant(ctx, guildID, roundID, participant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateParticipant", reflect.TypeOf((*MockRepository)(nil).UpdateParticipant), ctx, guildID, roundID, participant)
}

// UpdateParticipantScore mocks base method.
func (m *MockRepository) UpdateParticipantScore(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID, participantID sharedtypes.DiscordID, score sharedtypes.Score) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateParticipantScore", ctx, guildID, roundID, participantID, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateParticipantScore indicates an expected call of UpdateParticipantScore.
func (mr *MockRepositoryMockRecorder) UpdateParticipantScore(ctx, guildID, roundID, participantID, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateParticipantScore", reflect.TypeOf((*MockRepository)(nil).UpdateParticipantScore), ctx, guildID, roundID, participantID, score)
}

// UpdateRound mocks base method.
func (m *MockRepository) UpdateRound(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID, round *roundtypes.Round) (*roundtypes.Round, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRound", ctx, guildID, roundID, round)
	ret0, _ := ret[0].(*roundtypes.Round)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRound indicates an expected call of UpdateRound.
func (mr *MockRepositoryMockRecorder) UpdateRound(ctx, guildID, roundID, round any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRound", reflect.TypeOf((*MockRepository)(nil).UpdateRound), ctx, guildID, roundID, round)
}

// UpdateRoundState mocks base method.
func (m *MockRepository) UpdateRoundState(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID, state roundtypes.RoundState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoundState", ctx, guildID, roundID, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRoundState indicates an expected call of UpdateRoundState.
func (mr *MockRepositoryMockRecorder) UpdateRoundState(ctx, guildID, roundID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoundState", reflect.TypeOf((*MockRepository)(nil).UpdateRoundState), ctx, guildID, roundID, state)
}

// UpdateRoundsAndParticipants mocks base method.
func (m *MockRepository) UpdateRoundsAndParticipants(ctx context.Context, guildID sharedtypes.GuildID, updates []roundtypes.RoundUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoundsAndParticipants", ctx, guildID, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRoundsAndParticipants indicates an expected call of UpdateRoundsAndParticipants.
func (mr *MockRepositoryMockRecorder) UpdateRoundsAndParticipants(ctx, guildID, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoundsAndParticipants", reflect.TypeOf((*MockRepository)(nil).UpdateRoundsAndParticipants), ctx, guildID, updates)
}
