// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/modules/user/interfaces/handlers_interface.go
//
// Generated by this command:
//
//	mockgen -source=./app/modules/user/interfaces/handlers_interface.go -destination=./app/modules/user/infrastructure/handlers/mocks/mock_handlers.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	shared "github.com/Black-And-White-Club/tcr-bot/app/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockHandlers is a mock of Handlers interface.
type MockHandlers struct {
	ctrl     *gomock.Controller
	recorder *MockHandlersMockRecorder
	isgomock struct{}
}

// MockHandlersMockRecorder is the mock recorder for MockHandlers.
type MockHandlersMockRecorder struct {
	mock *MockHandlers
}

// NewMockHandlers creates a new mock instance.
func NewMockHandlers(ctrl *gomock.Controller) *MockHandlers {
	mock := &MockHandlers{ctrl: ctrl}
	mock.recorder = &MockHandlersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlers) EXPECT() *MockHandlersMockRecorder {
	return m.recorder
}

// HandleUserRoleUpdateRequest mocks base method.
func (m *MockHandlers) HandleUserRoleUpdateRequest(ctx context.Context, msg shared.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUserRoleUpdateRequest", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleUserRoleUpdateRequest indicates an expected call of HandleUserRoleUpdateRequest.
func (mr *MockHandlersMockRecorder) HandleUserRoleUpdateRequest(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUserRoleUpdateRequest", reflect.TypeOf((*MockHandlers)(nil).HandleUserRoleUpdateRequest), ctx, msg)
}

// HandleUserSignupRequest mocks base method.
func (m *MockHandlers) HandleUserSignupRequest(ctx context.Context, msg shared.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUserSignupRequest", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleUserSignupRequest indicates an expected call of HandleUserSignupRequest.
func (mr *MockHandlersMockRecorder) HandleUserSignupRequest(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUserSignupRequest", reflect.TypeOf((*MockHandlers)(nil).HandleUserSignupRequest), ctx, msg)
}
