// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/modules/score/infrastructure/repositories/interface.go
//
// Generated by this command:
//
//	mockgen -source=./app/modules/score/infrastructure/repositories/interface.go -destination=./app/modules/score/infrastructure/repositories/mocks/mock_db.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sharedtypes "github.com/Black-And-White-Club/frolf-bot-shared/types/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetScoresForRound mocks base method.
func (m *MockRepository) GetScoresForRound(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID) ([]sharedtypes.ScoreInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScoresForRound", ctx, guildID, roundID)
	ret0, _ := ret[0].([]sharedtypes.ScoreInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScoresForRound indicates an expected call of GetScoresForRound.
func (mr *MockRepositoryMockRecorder) GetScoresForRound(ctx, guildID, roundID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScoresForRound", reflect.TypeOf((*MockRepository)(nil).GetScoresForRound), ctx, guildID, roundID)
}

// LogScores mocks base method.
func (m *MockRepository) LogScores(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID, scores []sharedtypes.ScoreInfo, source string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogScores", ctx, guildID, roundID, scores, source)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogScores indicates an expected call of LogScores.
func (mr *MockRepositoryMockRecorder) LogScores(ctx, guildID, roundID, scores, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogScores", reflect.TypeOf((*MockRepository)(nil).LogScores), ctx, guildID, roundID, scores, source)
}

// UpdateOrAddScore mocks base method.
func (m *MockRepository) UpdateOrAddScore(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID, scoreInfo sharedtypes.ScoreInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrAddScore", ctx, guildID, roundID, scoreInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrAddScore indicates an expected call of UpdateOrAddScore.
func (mr *MockRepositoryMockRecorder) UpdateOrAddScore(ctx, guildID, roundID, scoreInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrAddScore", reflect.TypeOf((*MockRepository)(nil).UpdateOrAddScore), ctx, guildID, roundID, scoreInfo)
}

// UpdateScore mocks base method.
func (m *MockRepository) UpdateScore(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID, userID sharedtypes.DiscordID, newScore sharedtypes.Score) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScore", ctx, guildID, roundID, userID, newScore)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScore indicates an expected call of UpdateScore.
func (mr *MockRepositoryMockRecorder) UpdateScore(ctx, guildID, roundID, userID, newScore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScore", reflect.TypeOf((*MockRepository)(nil).UpdateScore), ctx, guildID, roundID, userID, newScore)
}
