package scoredb

import (
	sharedtypes "github.com/Black-And-White-Club/frolf-bot-shared/types/shared"
	"github.com/uptrace/bun"
)

// Score represents a score with round information.
type Score struct {
	bun.BaseModel `bun:"table:scores,alias:s"`
	// RoundID is the UUID generated by the round module for the specific round.
	RoundID   sharedtypes.RoundID     `bun:"id,pk,type:uuid"`
	RoundData []sharedtypes.ScoreInfo `bun:"round_data,type:jsonb,notnull"`
	Source    string                  `bun:"source,notnull"`
}
