// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/modules/user/infrastructure/repositories/interface.go
//
// Generated by this command:
//
//	mockgen -source=./app/modules/user/infrastructure/repositories/interface.go -destination=./app/modules/user/infrastructure/repositories/mocks/mock_db.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sharedtypes "github.com/Black-And-White-Club/frolf-bot-shared/types/shared"
	userdb "github.com/Black-And-White-Club/frolf-bot/app/modules/user/infrastructure/repositories"
	gomock "go.uber.org/mock/gomock"
)

// MockUserDB is a mock of UserDB interface.
type MockUserDB struct {
	ctrl     *gomock.Controller
	recorder *MockUserDBMockRecorder
	isgomock struct{}
}

// MockUserDBMockRecorder is the mock recorder for MockUserDB.
type MockUserDBMockRecorder struct {
	mock *MockUserDB
}

// NewMockUserDB creates a new mock instance.
func NewMockUserDB(ctrl *gomock.Controller) *MockUserDB {
	mock := &MockUserDB{ctrl: ctrl}
	mock.recorder = &MockUserDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDB) EXPECT() *MockUserDBMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserDB) CreateUser(ctx context.Context, user *userdb.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserDBMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserDB)(nil).CreateUser), ctx, user)
}

// FindByUDiscName mocks base method.
func (m *MockUserDB) FindByUDiscName(ctx context.Context, guildID sharedtypes.GuildID, name string) (*userdb.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUDiscName", ctx, guildID, name)
	ret0, _ := ret[0].(*userdb.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUDiscName indicates an expected call of FindByUDiscName.
func (mr *MockUserDBMockRecorder) FindByUDiscName(ctx, guildID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUDiscName", reflect.TypeOf((*MockUserDB)(nil).FindByUDiscName), ctx, guildID, name)
}

// FindByUDiscUsername mocks base method.
func (m *MockUserDB) FindByUDiscUsername(ctx context.Context, guildID sharedtypes.GuildID, username string) (*userdb.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUDiscUsername", ctx, guildID, username)
	ret0, _ := ret[0].(*userdb.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUDiscUsername indicates an expected call of FindByUDiscUsername.
func (mr *MockUserDBMockRecorder) FindByUDiscUsername(ctx, guildID, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUDiscUsername", reflect.TypeOf((*MockUserDB)(nil).FindByUDiscUsername), ctx, guildID, username)
}

// GetUserByUserID mocks base method.
func (m *MockUserDB) GetUserByUserID(ctx context.Context, userID sharedtypes.DiscordID, guildID sharedtypes.GuildID) (*userdb.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUserID", ctx, userID, guildID)
	ret0, _ := ret[0].(*userdb.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUserID indicates an expected call of GetUserByUserID.
func (mr *MockUserDBMockRecorder) GetUserByUserID(ctx, userID, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUserID", reflect.TypeOf((*MockUserDB)(nil).GetUserByUserID), ctx, userID, guildID)
}

// GetUserRole mocks base method.
func (m *MockUserDB) GetUserRole(ctx context.Context, userID sharedtypes.DiscordID, guildID sharedtypes.GuildID) (sharedtypes.UserRoleEnum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRole", ctx, userID, guildID)
	ret0, _ := ret[0].(sharedtypes.UserRoleEnum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockUserDBMockRecorder) GetUserRole(ctx, userID, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRole", reflect.TypeOf((*MockUserDB)(nil).GetUserRole), ctx, userID, guildID)
}

// UpdateUDiscIdentity mocks base method.
func (m *MockUserDB) UpdateUDiscIdentity(ctx context.Context, guildID sharedtypes.GuildID, userID sharedtypes.DiscordID, username, name *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUDiscIdentity", ctx, guildID, userID, username, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUDiscIdentity indicates an expected call of UpdateUDiscIdentity.
func (mr *MockUserDBMockRecorder) UpdateUDiscIdentity(ctx, guildID, userID, username, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUDiscIdentity", reflect.TypeOf((*MockUserDB)(nil).UpdateUDiscIdentity), ctx, guildID, userID, username, name)
}

// UpdateUserRole mocks base method.
func (m *MockUserDB) UpdateUserRole(ctx context.Context, userID sharedtypes.DiscordID, guildID sharedtypes.GuildID, role sharedtypes.UserRoleEnum) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRole", ctx, userID, guildID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserRole indicates an expected call of UpdateUserRole.
func (mr *MockUserDBMockRecorder) UpdateUserRole(ctx, userID, guildID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRole", reflect.TypeOf((*MockUserDB)(nil).UpdateUserRole), ctx, userID, guildID, role)
}
