// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/modules/user/infrastructure/repositories/interface.go
//
// Generated by this command:
//
//	mockgen -source=./app/modules/user/infrastructure/repositories/interface.go -destination=./app/modules/user/infrastructure/repositories/mocks/mock_db.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sharedtypes "github.com/Black-And-White-Club/frolf-bot-shared/types/shared"
	userdb "github.com/Black-And-White-Club/frolf-bot/app/modules/user/infrastructure/repositories"
	gomock "go.uber.org/mock/gomock"
)

// MockUserDB is a mock of UserDB interface.
type MockUserDB struct {
	ctrl     *gomock.Controller
	recorder *MockUserDBMockRecorder
	isgomock struct{}
}

// MockUserDBMockRecorder is the mock recorder for MockUserDB.
type MockUserDBMockRecorder struct {
	mock *MockUserDB
}

// NewMockUserDB creates a new mock instance.
func NewMockUserDB(ctrl *gomock.Controller) *MockUserDB {
	mock := &MockUserDB{ctrl: ctrl}
	mock.recorder = &MockUserDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDB) EXPECT() *MockUserDBMockRecorder {
	return m.recorder
}

// CreateGlobalUser mocks base method.
func (m *MockUserDB) CreateGlobalUser(ctx context.Context, user *userdb.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGlobalUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGlobalUser indicates an expected call of CreateGlobalUser.
func (mr *MockUserDBMockRecorder) CreateGlobalUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGlobalUser", reflect.TypeOf((*MockUserDB)(nil).CreateGlobalUser), ctx, user)
}

// CreateGuildMembership mocks base method.
func (m *MockUserDB) CreateGuildMembership(ctx context.Context, membership *userdb.GuildMembership) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGuildMembership", ctx, membership)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGuildMembership indicates an expected call of CreateGuildMembership.
func (mr *MockUserDBMockRecorder) CreateGuildMembership(ctx, membership any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGuildMembership", reflect.TypeOf((*MockUserDB)(nil).CreateGuildMembership), ctx, membership)
}

// FindByUDiscName mocks base method.
func (m *MockUserDB) FindByUDiscName(ctx context.Context, guildID sharedtypes.GuildID, name string) (*userdb.UserWithMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUDiscName", ctx, guildID, name)
	ret0, _ := ret[0].(*userdb.UserWithMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUDiscName indicates an expected call of FindByUDiscName.
func (mr *MockUserDBMockRecorder) FindByUDiscName(ctx, guildID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUDiscName", reflect.TypeOf((*MockUserDB)(nil).FindByUDiscName), ctx, guildID, name)
}

// FindByUDiscUsername mocks base method.
func (m *MockUserDB) FindByUDiscUsername(ctx context.Context, guildID sharedtypes.GuildID, username string) (*userdb.UserWithMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUDiscUsername", ctx, guildID, username)
	ret0, _ := ret[0].(*userdb.UserWithMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUDiscUsername indicates an expected call of FindByUDiscUsername.
func (mr *MockUserDBMockRecorder) FindByUDiscUsername(ctx, guildID, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUDiscUsername", reflect.TypeOf((*MockUserDB)(nil).FindByUDiscUsername), ctx, guildID, username)
}

// GetGuildMembership mocks base method.
func (m *MockUserDB) GetGuildMembership(ctx context.Context, userID sharedtypes.DiscordID, guildID sharedtypes.GuildID) (*userdb.GuildMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGuildMembership", ctx, userID, guildID)
	ret0, _ := ret[0].(*userdb.GuildMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGuildMembership indicates an expected call of GetGuildMembership.
func (mr *MockUserDBMockRecorder) GetGuildMembership(ctx, userID, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGuildMembership", reflect.TypeOf((*MockUserDB)(nil).GetGuildMembership), ctx, userID, guildID)
}

// GetUserByUserID mocks base method.
func (m *MockUserDB) GetUserByUserID(ctx context.Context, userID sharedtypes.DiscordID, guildID sharedtypes.GuildID) (*userdb.UserWithMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUserID", ctx, userID, guildID)
	ret0, _ := ret[0].(*userdb.UserWithMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUserID indicates an expected call of GetUserByUserID.
func (mr *MockUserDBMockRecorder) GetUserByUserID(ctx, userID, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUserID", reflect.TypeOf((*MockUserDB)(nil).GetUserByUserID), ctx, userID, guildID)
}

// GetUserGlobal mocks base method.
func (m *MockUserDB) GetUserGlobal(ctx context.Context, userID sharedtypes.DiscordID) (*userdb.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserGlobal", ctx, userID)
	ret0, _ := ret[0].(*userdb.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserGlobal indicates an expected call of GetUserGlobal.
func (mr *MockUserDBMockRecorder) GetUserGlobal(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserGlobal", reflect.TypeOf((*MockUserDB)(nil).GetUserGlobal), ctx, userID)
}

// GetUserMemberships mocks base method.
func (m *MockUserDB) GetUserMemberships(ctx context.Context, userID sharedtypes.DiscordID) ([]*userdb.GuildMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserMemberships", ctx, userID)
	ret0, _ := ret[0].([]*userdb.GuildMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserMemberships indicates an expected call of GetUserMemberships.
func (mr *MockUserDBMockRecorder) GetUserMemberships(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserMemberships", reflect.TypeOf((*MockUserDB)(nil).GetUserMemberships), ctx, userID)
}

// GetUserRole mocks base method.
func (m *MockUserDB) GetUserRole(ctx context.Context, userID sharedtypes.DiscordID, guildID sharedtypes.GuildID) (sharedtypes.UserRoleEnum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRole", ctx, userID, guildID)
	ret0, _ := ret[0].(sharedtypes.UserRoleEnum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockUserDBMockRecorder) GetUserRole(ctx, userID, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRole", reflect.TypeOf((*MockUserDB)(nil).GetUserRole), ctx, userID, guildID)
}

// UpdateMembershipRole mocks base method.
func (m *MockUserDB) UpdateMembershipRole(ctx context.Context, userID sharedtypes.DiscordID, guildID sharedtypes.GuildID, role sharedtypes.UserRoleEnum) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMembershipRole", ctx, userID, guildID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMembershipRole indicates an expected call of UpdateMembershipRole.
func (mr *MockUserDBMockRecorder) UpdateMembershipRole(ctx, userID, guildID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMembershipRole", reflect.TypeOf((*MockUserDB)(nil).UpdateMembershipRole), ctx, userID, guildID, role)
}

// UpdateUDiscIdentityGlobal mocks base method.
func (m *MockUserDB) UpdateUDiscIdentityGlobal(ctx context.Context, userID sharedtypes.DiscordID, username, name *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUDiscIdentityGlobal", ctx, userID, username, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUDiscIdentityGlobal indicates an expected call of UpdateUDiscIdentityGlobal.
func (mr *MockUserDBMockRecorder) UpdateUDiscIdentityGlobal(ctx, userID, username, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUDiscIdentityGlobal", reflect.TypeOf((*MockUserDB)(nil).UpdateUDiscIdentityGlobal), ctx, userID, username, name)
}

// UpdateUserRole mocks base method.
func (m *MockUserDB) UpdateUserRole(ctx context.Context, userID sharedtypes.DiscordID, guildID sharedtypes.GuildID, role sharedtypes.UserRoleEnum) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRole", ctx, userID, guildID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserRole indicates an expected call of UpdateUserRole.
func (mr *MockUserDBMockRecorder) UpdateUserRole(ctx, userID, guildID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRole", reflect.TypeOf((*MockUserDB)(nil).UpdateUserRole), ctx, userID, guildID, role)
}
