// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/modules/guild/infrastructure/handlers/interface.go
//
// Generated by this command:
//
//	mockgen -source=./app/modules/guild/infrastructure/handlers/interface.go -destination=./app/modules/guild/infrastructure/handlers/mocks/mock_handlers.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	guildevents "github.com/Black-And-White-Club/frolf-bot-shared/events/guild"
	guildtypes "github.com/Black-And-White-Club/frolf-bot-shared/types/guild"
	handlerwrapper "github.com/Black-And-White-Club/frolf-bot-shared/utils/handlerwrapper"
	gomock "go.uber.org/mock/gomock"
)

// MockHandlers is a mock of Handlers interface.
type MockHandlers struct {
	ctrl     *gomock.Controller
	recorder *MockHandlersMockRecorder
	isgomock struct{}
}

// MockHandlersMockRecorder is the mock recorder for MockHandlers.
type MockHandlersMockRecorder struct {
	mock *MockHandlers
}

// NewMockHandlers creates a new mock instance.
func NewMockHandlers(ctrl *gomock.Controller) *MockHandlers {
	mock := &MockHandlers{ctrl: ctrl}
	mock.recorder = &MockHandlersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlers) EXPECT() *MockHandlersMockRecorder {
	return m.recorder
}

// HandleCreateGuildConfig mocks base method.
func (m *MockHandlers) HandleCreateGuildConfig(ctx context.Context, payload *guildevents.GuildConfigCreationRequestedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCreateGuildConfig", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleCreateGuildConfig indicates an expected call of HandleCreateGuildConfig.
func (mr *MockHandlersMockRecorder) HandleCreateGuildConfig(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCreateGuildConfig", reflect.TypeOf((*MockHandlers)(nil).HandleCreateGuildConfig), ctx, payload)
}

// HandleDeleteGuildConfig mocks base method.
func (m *MockHandlers) HandleDeleteGuildConfig(ctx context.Context, payload *guildevents.GuildConfigDeletionRequestedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleDeleteGuildConfig", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleDeleteGuildConfig indicates an expected call of HandleDeleteGuildConfig.
func (mr *MockHandlersMockRecorder) HandleDeleteGuildConfig(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDeleteGuildConfig", reflect.TypeOf((*MockHandlers)(nil).HandleDeleteGuildConfig), ctx, payload)
}

// HandleGuildSetup mocks base method.
func (m *MockHandlers) HandleGuildSetup(ctx context.Context, payload *guildtypes.GuildConfig) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleGuildSetup", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleGuildSetup indicates an expected call of HandleGuildSetup.
func (mr *MockHandlersMockRecorder) HandleGuildSetup(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGuildSetup", reflect.TypeOf((*MockHandlers)(nil).HandleGuildSetup), ctx, payload)
}

// HandleRetrieveGuildConfig mocks base method.
func (m *MockHandlers) HandleRetrieveGuildConfig(ctx context.Context, payload *guildevents.GuildConfigRetrievalRequestedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleRetrieveGuildConfig", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleRetrieveGuildConfig indicates an expected call of HandleRetrieveGuildConfig.
func (mr *MockHandlersMockRecorder) HandleRetrieveGuildConfig(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRetrieveGuildConfig", reflect.TypeOf((*MockHandlers)(nil).HandleRetrieveGuildConfig), ctx, payload)
}

// HandleUpdateGuildConfig mocks base method.
func (m *MockHandlers) HandleUpdateGuildConfig(ctx context.Context, payload *guildevents.GuildConfigUpdateRequestedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUpdateGuildConfig", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleUpdateGuildConfig indicates an expected call of HandleUpdateGuildConfig.
func (mr *MockHandlersMockRecorder) HandleUpdateGuildConfig(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUpdateGuildConfig", reflect.TypeOf((*MockHandlers)(nil).HandleUpdateGuildConfig), ctx, payload)
}
