// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/modules/leaderboard/infrastructure/handlers/interface.go
//
// Generated by this command:
//
//	mockgen -source=./app/modules/leaderboard/infrastructure/handlers/interface.go -destination=./app/modules/leaderboard/infrastructure/handlers/mocks/mock_handlers.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	guildevents "github.com/Black-And-White-Club/frolf-bot-shared/events/guild"
	leaderboardevents "github.com/Black-And-White-Club/frolf-bot-shared/events/leaderboard"
	sharedevents "github.com/Black-And-White-Club/frolf-bot-shared/events/shared"
	handlerwrapper "github.com/Black-And-White-Club/frolf-bot-shared/utils/handlerwrapper"
	gomock "go.uber.org/mock/gomock"
)

// MockHandlers is a mock of Handlers interface.
type MockHandlers struct {
	ctrl     *gomock.Controller
	recorder *MockHandlersMockRecorder
	isgomock struct{}
}

// MockHandlersMockRecorder is the mock recorder for MockHandlers.
type MockHandlersMockRecorder struct {
	mock *MockHandlers
}

// NewMockHandlers creates a new mock instance.
func NewMockHandlers(ctrl *gomock.Controller) *MockHandlers {
	mock := &MockHandlers{ctrl: ctrl}
	mock.recorder = &MockHandlersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlers) EXPECT() *MockHandlersMockRecorder {
	return m.recorder
}

// HandleBatchTagAssignmentRequested mocks base method.
func (m *MockHandlers) HandleBatchTagAssignmentRequested(ctx context.Context, payload *sharedevents.BatchTagAssignmentRequestedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleBatchTagAssignmentRequested", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleBatchTagAssignmentRequested indicates an expected call of HandleBatchTagAssignmentRequested.
func (mr *MockHandlersMockRecorder) HandleBatchTagAssignmentRequested(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleBatchTagAssignmentRequested", reflect.TypeOf((*MockHandlers)(nil).HandleBatchTagAssignmentRequested), ctx, payload)
}

// HandleGetLeaderboardRequest mocks base method.
func (m *MockHandlers) HandleGetLeaderboardRequest(ctx context.Context, payload *leaderboardevents.GetLeaderboardRequestedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleGetLeaderboardRequest", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleGetLeaderboardRequest indicates an expected call of HandleGetLeaderboardRequest.
func (mr *MockHandlersMockRecorder) HandleGetLeaderboardRequest(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGetLeaderboardRequest", reflect.TypeOf((*MockHandlers)(nil).HandleGetLeaderboardRequest), ctx, payload)
}

// HandleGetTagByUserIDRequest mocks base method.
func (m *MockHandlers) HandleGetTagByUserIDRequest(ctx context.Context, payload *sharedevents.DiscordTagLookupRequestedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleGetTagByUserIDRequest", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleGetTagByUserIDRequest indicates an expected call of HandleGetTagByUserIDRequest.
func (mr *MockHandlersMockRecorder) HandleGetTagByUserIDRequest(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGetTagByUserIDRequest", reflect.TypeOf((*MockHandlers)(nil).HandleGetTagByUserIDRequest), ctx, payload)
}

// HandleGuildConfigCreated mocks base method.
func (m *MockHandlers) HandleGuildConfigCreated(ctx context.Context, payload *guildevents.GuildConfigCreatedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleGuildConfigCreated", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleGuildConfigCreated indicates an expected call of HandleGuildConfigCreated.
func (mr *MockHandlersMockRecorder) HandleGuildConfigCreated(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGuildConfigCreated", reflect.TypeOf((*MockHandlers)(nil).HandleGuildConfigCreated), ctx, payload)
}

// HandleLeaderboardUpdateRequested mocks base method.
func (m *MockHandlers) HandleLeaderboardUpdateRequested(ctx context.Context, payload *leaderboardevents.LeaderboardUpdateRequestedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleLeaderboardUpdateRequested", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleLeaderboardUpdateRequested indicates an expected call of HandleLeaderboardUpdateRequested.
func (mr *MockHandlersMockRecorder) HandleLeaderboardUpdateRequested(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleLeaderboardUpdateRequested", reflect.TypeOf((*MockHandlers)(nil).HandleLeaderboardUpdateRequested), ctx, payload)
}

// HandleRoundGetTagRequest mocks base method.
func (m *MockHandlers) HandleRoundGetTagRequest(ctx context.Context, payload *sharedevents.RoundTagLookupRequestedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleRoundGetTagRequest", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleRoundGetTagRequest indicates an expected call of HandleRoundGetTagRequest.
func (mr *MockHandlersMockRecorder) HandleRoundGetTagRequest(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRoundGetTagRequest", reflect.TypeOf((*MockHandlers)(nil).HandleRoundGetTagRequest), ctx, payload)
}

// HandleTagAvailabilityCheckRequested mocks base method.
func (m *MockHandlers) HandleTagAvailabilityCheckRequested(ctx context.Context, payload *leaderboardevents.TagAvailabilityCheckRequestedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleTagAvailabilityCheckRequested", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleTagAvailabilityCheckRequested indicates an expected call of HandleTagAvailabilityCheckRequested.
func (mr *MockHandlersMockRecorder) HandleTagAvailabilityCheckRequested(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleTagAvailabilityCheckRequested", reflect.TypeOf((*MockHandlers)(nil).HandleTagAvailabilityCheckRequested), ctx, payload)
}

// HandleTagSwapRequested mocks base method.
func (m *MockHandlers) HandleTagSwapRequested(ctx context.Context, payload *leaderboardevents.TagSwapRequestedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleTagSwapRequested", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleTagSwapRequested indicates an expected call of HandleTagSwapRequested.
func (mr *MockHandlersMockRecorder) HandleTagSwapRequested(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleTagSwapRequested", reflect.TypeOf((*MockHandlers)(nil).HandleTagSwapRequested), ctx, payload)
}
