// src/modules/user/user.entity.ts
import { IsString, IsNumber, IsOptional, IsEnum } from "class-validator";
import { UserRole } from "src/enums";

export class User {
  @IsNumber()
  id!: number; // Will be generated by the database

  @IsString()
  name!: string; // Required

  @IsString()
  discordID!: string; // Required and unique

  @IsEnum(UserRole)
  role: UserRole = UserRole.Rattler; // Default value

  @IsNumber()
  @IsOptional()
  tagNumber?: number;

  @IsString()
  createdAt!: string; // Will be generated by the database

  @IsString()
  updatedAt!: string; // Will be generated by the database

  @IsString()
  @IsOptional()
  deletedAt?: string;
}
