// Code generated by MockGen. DO NOT EDIT.
// Source: ./application/interface.go
//
// Generated by this command:
//
//	mockgen -source=./application/interface.go -destination=./application/mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	leaderboardevents "github.com/Black-And-White-Club/tcr-bot/app/modules/leaderboard/domain/events"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AssignTag mocks base method.
func (m *MockService) AssignTag(ctx context.Context, event leaderboardevents.TagAssignedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignTag", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignTag indicates an expected call of AssignTag.
func (mr *MockServiceMockRecorder) AssignTag(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignTag", reflect.TypeOf((*MockService)(nil).AssignTag), ctx, event)
}

// CheckTagAvailability mocks base method.
func (m *MockService) CheckTagAvailability(ctx context.Context, tagNumber int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckTagAvailability", ctx, tagNumber)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckTagAvailability indicates an expected call of CheckTagAvailability.
func (mr *MockServiceMockRecorder) CheckTagAvailability(ctx, tagNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckTagAvailability", reflect.TypeOf((*MockService)(nil).CheckTagAvailability), ctx, tagNumber)
}

// GetLeaderboard mocks base method.
func (m *MockService) GetLeaderboard(ctx context.Context) ([]leaderboardevents.LeaderboardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLeaderboard", ctx)
	ret0, _ := ret[0].([]leaderboardevents.LeaderboardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLeaderboard indicates an expected call of GetLeaderboard.
func (mr *MockServiceMockRecorder) GetLeaderboard(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLeaderboard", reflect.TypeOf((*MockService)(nil).GetLeaderboard), ctx)
}

// GetTagByDiscordID mocks base method.
func (m *MockService) GetTagByDiscordID(ctx context.Context, discordID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagByDiscordID", ctx, discordID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagByDiscordID indicates an expected call of GetTagByDiscordID.
func (mr *MockServiceMockRecorder) GetTagByDiscordID(ctx, discordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagByDiscordID", reflect.TypeOf((*MockService)(nil).GetTagByDiscordID), ctx, discordID)
}

// SwapTags mocks base method.
func (m *MockService) SwapTags(ctx context.Context, requestorID, targetID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwapTags", ctx, requestorID, targetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SwapTags indicates an expected call of SwapTags.
func (mr *MockServiceMockRecorder) SwapTags(ctx, requestorID, targetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwapTags", reflect.TypeOf((*MockService)(nil).SwapTags), ctx, requestorID, targetID)
}

// UpdateLeaderboard mocks base method.
func (m *MockService) UpdateLeaderboard(ctx context.Context, event leaderboardevents.LeaderboardUpdateEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLeaderboard", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLeaderboard indicates an expected call of UpdateLeaderboard.
func (mr *MockServiceMockRecorder) UpdateLeaderboard(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLeaderboard", reflect.TypeOf((*MockService)(nil).UpdateLeaderboard), ctx, event)
}
