// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/modules/score/infrastructure/handlers/interface.go
//
// Generated by this command:
//
//	mockgen -source=./app/modules/score/infrastructure/handlers/interface.go -destination=./app/modules/score/infrastructure/handlers/mocks/mock_handlers.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	scoreevents "github.com/Black-And-White-Club/frolf-bot-shared/events/score"
	handlerwrapper "github.com/Black-And-White-Club/frolf-bot-shared/utils/handlerwrapper"
	gomock "go.uber.org/mock/gomock"
)

// MockHandlers is a mock of Handlers interface.
type MockHandlers struct {
	ctrl     *gomock.Controller
	recorder *MockHandlersMockRecorder
	isgomock struct{}
}

// MockHandlersMockRecorder is the mock recorder for MockHandlers.
type MockHandlersMockRecorder struct {
	mock *MockHandlers
}

// NewMockHandlers creates a new mock instance.
func NewMockHandlers(ctrl *gomock.Controller) *MockHandlers {
	mock := &MockHandlers{ctrl: ctrl}
	mock.recorder = &MockHandlersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlers) EXPECT() *MockHandlersMockRecorder {
	return m.recorder
}

// HandleBulkCorrectScoreRequest mocks base method.
func (m *MockHandlers) HandleBulkCorrectScoreRequest(ctx context.Context, payload *scoreevents.ScoreBulkUpdateRequestPayload) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleBulkCorrectScoreRequest", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleBulkCorrectScoreRequest indicates an expected call of HandleBulkCorrectScoreRequest.
func (mr *MockHandlersMockRecorder) HandleBulkCorrectScoreRequest(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleBulkCorrectScoreRequest", reflect.TypeOf((*MockHandlers)(nil).HandleBulkCorrectScoreRequest), ctx, payload)
}

// HandleCorrectScoreRequest mocks base method.
func (m *MockHandlers) HandleCorrectScoreRequest(ctx context.Context, payload *scoreevents.ScoreUpdateRequestedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCorrectScoreRequest", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleCorrectScoreRequest indicates an expected call of HandleCorrectScoreRequest.
func (mr *MockHandlersMockRecorder) HandleCorrectScoreRequest(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCorrectScoreRequest", reflect.TypeOf((*MockHandlers)(nil).HandleCorrectScoreRequest), ctx, payload)
}

// HandleProcessRoundScoresRequest mocks base method.
func (m *MockHandlers) HandleProcessRoundScoresRequest(ctx context.Context, payload *scoreevents.ProcessRoundScoresRequestedPayloadV1) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleProcessRoundScoresRequest", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleProcessRoundScoresRequest indicates an expected call of HandleProcessRoundScoresRequest.
func (mr *MockHandlersMockRecorder) HandleProcessRoundScoresRequest(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleProcessRoundScoresRequest", reflect.TypeOf((*MockHandlers)(nil).HandleProcessRoundScoresRequest), ctx, payload)
}

// HandleReprocessAfterScoreUpdate mocks base method.
func (m *MockHandlers) HandleReprocessAfterScoreUpdate(ctx context.Context, payload any) ([]handlerwrapper.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleReprocessAfterScoreUpdate", ctx, payload)
	ret0, _ := ret[0].([]handlerwrapper.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleReprocessAfterScoreUpdate indicates an expected call of HandleReprocessAfterScoreUpdate.
func (mr *MockHandlersMockRecorder) HandleReprocessAfterScoreUpdate(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleReprocessAfterScoreUpdate", reflect.TypeOf((*MockHandlers)(nil).HandleReprocessAfterScoreUpdate), ctx, payload)
}
