// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/modules/score/application/interface.go
//
// Generated by this command:
//
//	mockgen -source=./app/modules/score/application/interface.go -destination=./app/modules/score/application/mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	scoreevents "github.com/Black-And-White-Club/tcr-bot/app/modules/score/domain/events"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CorrectScore mocks base method.
func (m *MockService) CorrectScore(ctx context.Context, event scoreevents.ScoreUpdateRequestPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CorrectScore", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CorrectScore indicates an expected call of CorrectScore.
func (mr *MockServiceMockRecorder) CorrectScore(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CorrectScore", reflect.TypeOf((*MockService)(nil).CorrectScore), ctx, event)
}

// ProcessRoundScores mocks base method.
func (m *MockService) ProcessRoundScores(ctx context.Context, event scoreevents.ProcessRoundScoresRequestPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessRoundScores", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessRoundScores indicates an expected call of ProcessRoundScores.
func (mr *MockServiceMockRecorder) ProcessRoundScores(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessRoundScores", reflect.TypeOf((*MockService)(nil).ProcessRoundScores), ctx, event)
}
