// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/modules/score/application/interface.go
//
// Generated by this command:
//
//	mockgen -source=./app/modules/score/application/interface.go -destination=./app/modules/score/application/mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	scoreevents "github.com/Black-And-White-Club/frolf-bot-shared/events/score"
	scoreservice "github.com/Black-And-White-Club/frolf-bot/app/modules/score/application"
	message "github.com/ThreeDotsLabs/watermill/message"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CorrectScore mocks base method.
func (m *MockService) CorrectScore(ctx context.Context, msg *message.Message, event scoreevents.ScoreUpdateRequestPayload) (scoreservice.ScoreOperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CorrectScore", ctx, msg, event)
	ret0, _ := ret[0].(scoreservice.ScoreOperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CorrectScore indicates an expected call of CorrectScore.
func (mr *MockServiceMockRecorder) CorrectScore(ctx, msg, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CorrectScore", reflect.TypeOf((*MockService)(nil).CorrectScore), ctx, msg, event)
}

// ProcessRoundScores mocks base method.
func (m *MockService) ProcessRoundScores(ctx context.Context, msg *message.Message, event scoreevents.ProcessRoundScoresRequestPayload) (scoreservice.ScoreOperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessRoundScores", ctx, msg, event)
	ret0, _ := ret[0].(scoreservice.ScoreOperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessRoundScores indicates an expected call of ProcessRoundScores.
func (mr *MockServiceMockRecorder) ProcessRoundScores(ctx, msg, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessRoundScores", reflect.TypeOf((*MockService)(nil).ProcessRoundScores), ctx, msg, event)
}
