// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/modules/leaderboard/infrastructure/saga/coordinator.go
//
// Generated by this command:
//
//	mockgen -source=./app/modules/leaderboard/infrastructure/saga/coordinator.go -destination=./app/modules/leaderboard/infrastructure/saga/mocks/mock_handlers.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
