// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/modules/round/domain/types/types.go
//
// Generated by this command:
//
//	mockgen -source=./app/modules/round/domain/types/types.go -destination=./app/modules/round/domain/types/mocks/mock_types.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
