// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/modules/round/application/interface.go
//
// Generated by this command:
//
//	mockgen -source=./app/modules/round/application/interface.go -destination=./app/modules/round/application/mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	roundevents "github.com/Black-And-White-Club/frolf-bot-shared/events/round"
	roundtypes "github.com/Black-And-White-Club/frolf-bot-shared/types/round"
	sharedtypes "github.com/Black-And-White-Club/frolf-bot-shared/types/shared"
	results "github.com/Black-And-White-Club/frolf-bot-shared/utils/results"
	roundtime "github.com/Black-And-White-Club/frolf-bot/app/modules/round/time_utils"
	roundutil "github.com/Black-And-White-Club/frolf-bot/app/modules/round/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ApplyImportedScores mocks base method.
func (m *MockService) ApplyImportedScores(ctx context.Context, payload roundevents.ImportCompletedPayloadV1) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyImportedScores", ctx, payload)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyImportedScores indicates an expected call of ApplyImportedScores.
func (mr *MockServiceMockRecorder) ApplyImportedScores(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyImportedScores", reflect.TypeOf((*MockService)(nil).ApplyImportedScores), ctx, payload)
}

// CheckAllScoresSubmitted mocks base method.
func (m *MockService) CheckAllScoresSubmitted(ctx context.Context, payload roundevents.ParticipantScoreUpdatedPayloadV1) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAllScoresSubmitted", ctx, payload)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAllScoresSubmitted indicates an expected call of CheckAllScoresSubmitted.
func (mr *MockServiceMockRecorder) CheckAllScoresSubmitted(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAllScoresSubmitted", reflect.TypeOf((*MockService)(nil).CheckAllScoresSubmitted), ctx, payload)
}

// CheckParticipantStatus mocks base method.
func (m *MockService) CheckParticipantStatus(ctx context.Context, payload roundevents.ParticipantJoinRequestPayloadV1) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckParticipantStatus", ctx, payload)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckParticipantStatus indicates an expected call of CheckParticipantStatus.
func (mr *MockServiceMockRecorder) CheckParticipantStatus(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckParticipantStatus", reflect.TypeOf((*MockService)(nil).CheckParticipantStatus), ctx, payload)
}

// CreateImportJob mocks base method.
func (m *MockService) CreateImportJob(ctx context.Context, payload roundevents.ScorecardUploadedPayloadV1) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateImportJob", ctx, payload)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateImportJob indicates an expected call of CreateImportJob.
func (mr *MockServiceMockRecorder) CreateImportJob(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateImportJob", reflect.TypeOf((*MockService)(nil).CreateImportJob), ctx, payload)
}

// DeleteRound mocks base method.
func (m *MockService) DeleteRound(ctx context.Context, payload roundevents.RoundDeleteAuthorizedPayloadV1) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRound", ctx, payload)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRound indicates an expected call of DeleteRound.
func (mr *MockServiceMockRecorder) DeleteRound(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRound", reflect.TypeOf((*MockService)(nil).DeleteRound), ctx, payload)
}

// FinalizeRound mocks base method.
func (m *MockService) FinalizeRound(ctx context.Context, payload roundevents.AllScoresSubmittedPayloadV1) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeRound", ctx, payload)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinalizeRound indicates an expected call of FinalizeRound.
func (mr *MockServiceMockRecorder) FinalizeRound(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeRound", reflect.TypeOf((*MockService)(nil).FinalizeRound), ctx, payload)
}

// GetRound mocks base method.
func (m *MockService) GetRound(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRound", ctx, guildID, roundID)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRound indicates an expected call of GetRound.
func (mr *MockServiceMockRecorder) GetRound(ctx, guildID, roundID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRound", reflect.TypeOf((*MockService)(nil).GetRound), ctx, guildID, roundID)
}

// GetRoundsForGuild mocks base method.
func (m *MockService) GetRoundsForGuild(ctx context.Context, guildID sharedtypes.GuildID) ([]*roundtypes.Round, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoundsForGuild", ctx, guildID)
	ret0, _ := ret[0].([]*roundtypes.Round)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoundsForGuild indicates an expected call of GetRoundsForGuild.
func (mr *MockServiceMockRecorder) GetRoundsForGuild(ctx, guildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoundsForGuild", reflect.TypeOf((*MockService)(nil).GetRoundsForGuild), ctx, guildID)
}

// IngestNormalizedScorecard mocks base method.
func (m *MockService) IngestNormalizedScorecard(ctx context.Context, payload roundevents.ScorecardNormalizedPayloadV1) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestNormalizedScorecard", ctx, payload)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IngestNormalizedScorecard indicates an expected call of IngestNormalizedScorecard.
func (mr *MockServiceMockRecorder) IngestNormalizedScorecard(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestNormalizedScorecard", reflect.TypeOf((*MockService)(nil).IngestNormalizedScorecard), ctx, payload)
}

// NormalizeParsedScorecard mocks base method.
func (m *MockService) NormalizeParsedScorecard(ctx context.Context, parsed *roundtypes.ParsedScorecard, meta roundtypes.Metadata) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NormalizeParsedScorecard", ctx, parsed, meta)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NormalizeParsedScorecard indicates an expected call of NormalizeParsedScorecard.
func (mr *MockServiceMockRecorder) NormalizeParsedScorecard(ctx, parsed, meta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NormalizeParsedScorecard", reflect.TypeOf((*MockService)(nil).NormalizeParsedScorecard), ctx, parsed, meta)
}

// NotifyScoreModule mocks base method.
func (m *MockService) NotifyScoreModule(ctx context.Context, payload roundevents.RoundFinalizedPayloadV1) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyScoreModule", ctx, payload)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotifyScoreModule indicates an expected call of NotifyScoreModule.
func (mr *MockServiceMockRecorder) NotifyScoreModule(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyScoreModule", reflect.TypeOf((*MockService)(nil).NotifyScoreModule), ctx, payload)
}

// ParseScorecard mocks base method.
func (m *MockService) ParseScorecard(ctx context.Context, payload roundevents.ScorecardUploadedPayloadV1, fileData []byte) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseScorecard", ctx, payload, fileData)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseScorecard indicates an expected call of ParseScorecard.
func (mr *MockServiceMockRecorder) ParseScorecard(ctx, payload, fileData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseScorecard", reflect.TypeOf((*MockService)(nil).ParseScorecard), ctx, payload, fileData)
}

// ParticipantRemoval mocks base method.
func (m *MockService) ParticipantRemoval(ctx context.Context, payload roundevents.ParticipantRemovalRequestPayloadV1) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParticipantRemoval", ctx, payload)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParticipantRemoval indicates an expected call of ParticipantRemoval.
func (mr *MockServiceMockRecorder) ParticipantRemoval(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParticipantRemoval", reflect.TypeOf((*MockService)(nil).ParticipantRemoval), ctx, payload)
}

// ProcessRoundReminder mocks base method.
func (m *MockService) ProcessRoundReminder(ctx context.Context, payload roundevents.DiscordReminderPayloadV1) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessRoundReminder", ctx, payload)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessRoundReminder indicates an expected call of ProcessRoundReminder.
func (mr *MockServiceMockRecorder) ProcessRoundReminder(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessRoundReminder", reflect.TypeOf((*MockService)(nil).ProcessRoundReminder), ctx, payload)
}

// ProcessRoundStart mocks base method.
func (m *MockService) ProcessRoundStart(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessRoundStart", ctx, guildID, roundID)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessRoundStart indicates an expected call of ProcessRoundStart.
func (mr *MockServiceMockRecorder) ProcessRoundStart(ctx, guildID, roundID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessRoundStart", reflect.TypeOf((*MockService)(nil).ProcessRoundStart), ctx, guildID, roundID)
}

// ScheduleRoundEvents mocks base method.
func (m *MockService) ScheduleRoundEvents(ctx context.Context, guildID sharedtypes.GuildID, payload roundevents.RoundScheduledPayloadV1, discordMessageID string) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScheduleRoundEvents", ctx, guildID, payload, discordMessageID)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScheduleRoundEvents indicates an expected call of ScheduleRoundEvents.
func (mr *MockServiceMockRecorder) ScheduleRoundEvents(ctx, guildID, payload, discordMessageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScheduleRoundEvents", reflect.TypeOf((*MockService)(nil).ScheduleRoundEvents), ctx, guildID, payload, discordMessageID)
}

// ScorecardURLRequested mocks base method.
func (m *MockService) ScorecardURLRequested(ctx context.Context, payload roundevents.ScorecardURLRequestedPayloadV1) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScorecardURLRequested", ctx, payload)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScorecardURLRequested indicates an expected call of ScorecardURLRequested.
func (mr *MockServiceMockRecorder) ScorecardURLRequested(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScorecardURLRequested", reflect.TypeOf((*MockService)(nil).ScorecardURLRequested), ctx, payload)
}

// StoreRound mocks base method.
func (m *MockService) StoreRound(ctx context.Context, guildID sharedtypes.GuildID, payload roundevents.RoundEntityCreatedPayloadV1) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRound", ctx, guildID, payload)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreRound indicates an expected call of StoreRound.
func (mr *MockServiceMockRecorder) StoreRound(ctx, guildID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRound", reflect.TypeOf((*MockService)(nil).StoreRound), ctx, guildID, payload)
}

// UpdateParticipantScore mocks base method.
func (m *MockService) UpdateParticipantScore(ctx context.Context, payload roundevents.ScoreUpdateValidatedPayloadV1) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateParticipantScore", ctx, payload)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateParticipantScore indicates an expected call of UpdateParticipantScore.
func (mr *MockServiceMockRecorder) UpdateParticipantScore(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateParticipantScore", reflect.TypeOf((*MockService)(nil).UpdateParticipantScore), ctx, payload)
}

// UpdateParticipantScoresBulk mocks base method.
func (m *MockService) UpdateParticipantScoresBulk(ctx context.Context, payload roundevents.ScoreBulkUpdateRequestPayloadV1) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateParticipantScoresBulk", ctx, payload)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateParticipantScoresBulk indicates an expected call of UpdateParticipantScoresBulk.
func (mr *MockServiceMockRecorder) UpdateParticipantScoresBulk(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateParticipantScoresBulk", reflect.TypeOf((*MockService)(nil).UpdateParticipantScoresBulk), ctx, payload)
}

// UpdateParticipantStatus mocks base method.
func (m *MockService) UpdateParticipantStatus(ctx context.Context, payload roundevents.ParticipantJoinRequestPayloadV1) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateParticipantStatus", ctx, payload)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateParticipantStatus indicates an expected call of UpdateParticipantStatus.
func (mr *MockServiceMockRecorder) UpdateParticipantStatus(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateParticipantStatus", reflect.TypeOf((*MockService)(nil).UpdateParticipantStatus), ctx, payload)
}

// UpdateRoundEntity mocks base method.
func (m *MockService) UpdateRoundEntity(ctx context.Context, payload roundevents.RoundUpdateValidatedPayloadV1) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoundEntity", ctx, payload)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRoundEntity indicates an expected call of UpdateRoundEntity.
func (mr *MockServiceMockRecorder) UpdateRoundEntity(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoundEntity", reflect.TypeOf((*MockService)(nil).UpdateRoundEntity), ctx, payload)
}

// UpdateRoundMessageID mocks base method.
func (m *MockService) UpdateRoundMessageID(ctx context.Context, guildID sharedtypes.GuildID, roundID sharedtypes.RoundID, discordMessageID string) (*roundtypes.Round, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoundMessageID", ctx, guildID, roundID, discordMessageID)
	ret0, _ := ret[0].(*roundtypes.Round)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRoundMessageID indicates an expected call of UpdateRoundMessageID.
func (mr *MockServiceMockRecorder) UpdateRoundMessageID(ctx, guildID, roundID, discordMessageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoundMessageID", reflect.TypeOf((*MockService)(nil).UpdateRoundMessageID), ctx, guildID, roundID, discordMessageID)
}

// UpdateScheduledRoundEvents mocks base method.
func (m *MockService) UpdateScheduledRoundEvents(ctx context.Context, payload roundevents.RoundScheduleUpdatePayloadV1) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScheduledRoundEvents", ctx, payload)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateScheduledRoundEvents indicates an expected call of UpdateScheduledRoundEvents.
func (mr *MockServiceMockRecorder) UpdateScheduledRoundEvents(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScheduledRoundEvents", reflect.TypeOf((*MockService)(nil).UpdateScheduledRoundEvents), ctx, payload)
}

// UpdateScheduledRoundsWithNewTags mocks base method.
func (m *MockService) UpdateScheduledRoundsWithNewTags(ctx context.Context, guildID sharedtypes.GuildID, changedTags map[sharedtypes.DiscordID]sharedtypes.TagNumber) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScheduledRoundsWithNewTags", ctx, guildID, changedTags)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateScheduledRoundsWithNewTags indicates an expected call of UpdateScheduledRoundsWithNewTags.
func (mr *MockServiceMockRecorder) UpdateScheduledRoundsWithNewTags(ctx, guildID, changedTags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScheduledRoundsWithNewTags", reflect.TypeOf((*MockService)(nil).UpdateScheduledRoundsWithNewTags), ctx, guildID, changedTags)
}

// ValidateAndProcessRoundUpdate mocks base method.
func (m *MockService) ValidateAndProcessRoundUpdate(ctx context.Context, payload roundevents.UpdateRoundRequestedPayloadV1, timeParser roundtime.TimeParserInterface) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndProcessRoundUpdate", ctx, payload, timeParser)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAndProcessRoundUpdate indicates an expected call of ValidateAndProcessRoundUpdate.
func (mr *MockServiceMockRecorder) ValidateAndProcessRoundUpdate(ctx, payload, timeParser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndProcessRoundUpdate", reflect.TypeOf((*MockService)(nil).ValidateAndProcessRoundUpdate), ctx, payload, timeParser)
}

// ValidateAndProcessRoundUpdateWithClock mocks base method.
func (m *MockService) ValidateAndProcessRoundUpdateWithClock(ctx context.Context, payload roundevents.UpdateRoundRequestedPayloadV1, timeParser roundtime.TimeParserInterface, clock roundutil.Clock) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndProcessRoundUpdateWithClock", ctx, payload, timeParser, clock)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAndProcessRoundUpdateWithClock indicates an expected call of ValidateAndProcessRoundUpdateWithClock.
func (mr *MockServiceMockRecorder) ValidateAndProcessRoundUpdateWithClock(ctx, payload, timeParser, clock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndProcessRoundUpdateWithClock", reflect.TypeOf((*MockService)(nil).ValidateAndProcessRoundUpdateWithClock), ctx, payload, timeParser, clock)
}

// ValidateAndProcessRoundWithClock mocks base method.
func (m *MockService) ValidateAndProcessRoundWithClock(ctx context.Context, payload roundevents.CreateRoundRequestedPayloadV1, timeParser roundtime.TimeParserInterface, clock roundutil.Clock) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndProcessRoundWithClock", ctx, payload, timeParser, clock)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAndProcessRoundWithClock indicates an expected call of ValidateAndProcessRoundWithClock.
func (mr *MockServiceMockRecorder) ValidateAndProcessRoundWithClock(ctx, payload, timeParser, clock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndProcessRoundWithClock", reflect.TypeOf((*MockService)(nil).ValidateAndProcessRoundWithClock), ctx, payload, timeParser, clock)
}

// ValidateParticipantJoinRequest mocks base method.
func (m *MockService) ValidateParticipantJoinRequest(ctx context.Context, payload roundevents.ParticipantJoinRequestPayloadV1) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateParticipantJoinRequest", ctx, payload)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateParticipantJoinRequest indicates an expected call of ValidateParticipantJoinRequest.
func (mr *MockServiceMockRecorder) ValidateParticipantJoinRequest(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateParticipantJoinRequest", reflect.TypeOf((*MockService)(nil).ValidateParticipantJoinRequest), ctx, payload)
}

// ValidateRoundDeleteRequest mocks base method.
func (m *MockService) ValidateRoundDeleteRequest(ctx context.Context, payload roundevents.RoundDeleteRequestPayloadV1) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRoundDeleteRequest", ctx, payload)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateRoundDeleteRequest indicates an expected call of ValidateRoundDeleteRequest.
func (mr *MockServiceMockRecorder) ValidateRoundDeleteRequest(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRoundDeleteRequest", reflect.TypeOf((*MockService)(nil).ValidateRoundDeleteRequest), ctx, payload)
}

// ValidateScoreUpdateRequest mocks base method.
func (m *MockService) ValidateScoreUpdateRequest(ctx context.Context, payload roundevents.ScoreUpdateRequestPayloadV1) (results.OperationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateScoreUpdateRequest", ctx, payload)
	ret0, _ := ret[0].(results.OperationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateScoreUpdateRequest indicates an expected call of ValidateScoreUpdateRequest.
func (mr *MockServiceMockRecorder) ValidateScoreUpdateRequest(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateScoreUpdateRequest", reflect.TypeOf((*MockService)(nil).ValidateScoreUpdateRequest), ctx, payload)
}
